apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-deployment
  labels:
    app: sai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sai-sai
  template:
    metadata:
      labels:
        app: sai-saipod
    spec:
      containers:
      - name: sai-sai
        image: vamshi5022/sample1javacode:v3
        imagePullPolicy: Always  
        ports:
        - containerPort: 80

           
